#!/usr/bin/env python3
"""
Create a retrieval index from webpage descriptions generated by generate_descriptions_url_tree.py

This script creates semantic embeddings from webpage descriptions to enable
retrieval of similar webpages based on functionality and content.
"""

from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pickle
import json
import argparse
import os
from typing import Dict, List, Tuple, Optional
from datetime import datetime


def load_webpage_descriptions(descriptions_file: str) -> Dict[str, str]:
    """
    Load webpage descriptions from the JSON file generated by generate_descriptions_url_tree.py
    
    Args:
        descriptions_file: Path to the JSON file with URL -> description mappings
    
    Returns:
        Dictionary with normalized URLs as keys and descriptions as values
    """
    try:
        with open(descriptions_file, 'r', encoding='utf-8') as f:
            descriptions = json.load(f)
        print(f"Loaded {len(descriptions)} webpage descriptions from {descriptions_file}")
        return descriptions
    except FileNotFoundError:
        raise FileNotFoundError(f"Descriptions file not found: {descriptions_file}")
    except json.JSONDecodeError as e:
        raise ValueError(f"Error parsing JSON from {descriptions_file}: {e}")


def create_webpage_retrieval_index(descriptions: Dict[str, str], 
                                 model_name: str = 'all-MiniLM-L6-v2') -> Dict:
    """
    Create a retrieval index from webpage descriptions using sentence embeddings.
    
    Args:
        descriptions: Dictionary with URLs as keys and descriptions as values
        model_name: Name of the sentence transformer model to use
    
    Returns:
        Dictionary containing embeddings, URLs, descriptions, and model for retrieval
    """
    print(f"Creating retrieval index with model: {model_name}")
    
    # Initialize sentence transformer model
    model = SentenceTransformer(model_name)
    
    # Prepare data for indexing
    urls = list(descriptions.keys())
    description_texts = list(descriptions.values())
    
    # Filter out any empty descriptions
    valid_items = [(url, desc) for url, desc in zip(urls, description_texts) 
                   if desc and desc.strip() and not desc.startswith("Error")]
    
    if not valid_items:
        raise ValueError("No valid descriptions found for indexing")
    
    valid_urls, valid_descriptions = zip(*valid_items)
    valid_urls = list(valid_urls)
    valid_descriptions = list(valid_descriptions)
    
    print(f"Creating embeddings for {len(valid_descriptions)} valid webpage descriptions...")
    
    # Generate embeddings for all descriptions
    embeddings = model.encode(valid_descriptions, show_progress_bar=True)
    
    # Create the retrieval index
    index = {
        'embeddings': embeddings,
        'urls': valid_urls,
        'descriptions': valid_descriptions,
        'model': model,
        'model_name': model_name,
        'creation_timestamp': datetime.now().isoformat(),
        'total_webpages': len(valid_descriptions)
    }
    
    print(f"Successfully created index with {len(valid_descriptions)} webpages")
    return index


def retrieve_similar_webpages(query: str, 
                             index: Dict, 
                             top_k: int = 10, 
                             similarity_threshold: float = 0.3) -> List[Dict]:
    """
    Retrieve webpages with descriptions similar to the query.
    
    Args:
        query: Query text to find similar webpages
        index: The retrieval index
        top_k: Number of top results to return
        similarity_threshold: Minimum similarity score
    
    Returns:
        List of similar webpages with URLs, descriptions, and similarity scores
    """
    # Encode the query
    query_embedding = index['model'].encode([query])
    
    # Calculate similarities
    similarities = cosine_similarity(query_embedding, index['embeddings'])[0]
    
    # Get top-k most similar webpages
    top_indices = np.argsort(similarities)[::-1][:top_k]
    
    results = []
    for idx in top_indices:
        if similarities[idx] >= similarity_threshold:
            results.append({
                'url': index['urls'][idx],
                'description': index['descriptions'][idx],
                'similarity_score': float(similarities[idx])
            })
    
    return results


def find_webpages_by_functionality(functionality_keywords: List[str],
                                 index: Dict,
                                 top_k: int = 10,
                                 similarity_threshold: float = 0.3) -> List[Dict]:
    """
    Find webpages that match specific functionality keywords.
    
    Args:
        functionality_keywords: List of functionality-related keywords
        index: The retrieval index
        top_k: Number of top results to return
        similarity_threshold: Minimum similarity score
    
    Returns:
        List of webpages matching the functionality criteria
    """
    # Create a query from functionality keywords
    query = f"webpage functionality: {', '.join(functionality_keywords)}"
    return retrieve_similar_webpages(query, index, top_k, similarity_threshold)


def group_similar_webpages(index: Dict, 
                          similarity_threshold: float = 0.7,
                          max_group_size: int = 10) -> List[List[Dict]]:
    """
    Group webpages with similar functionality together.
    
    Args:
        index: The retrieval index
        similarity_threshold: Minimum similarity to group webpages together
        max_group_size: Maximum number of webpages per group
    
    Returns:
        List of groups, where each group is a list of similar webpages
    """
    print(f"Grouping similar webpages with threshold {similarity_threshold}...")
    
    embeddings = index['embeddings']
    urls = index['urls']
    descriptions = index['descriptions']
    
    # Calculate pairwise similarities
    similarity_matrix = cosine_similarity(embeddings)
    
    # Group similar webpages
    groups = []
    used_indices = set()
    
    for i in range(len(embeddings)):
        if i in used_indices:
            continue
            
        # Find all webpages similar to this one
        similar_indices = [i]
        for j in range(i + 1, len(embeddings)):
            if j not in used_indices and similarity_matrix[i][j] >= similarity_threshold:
                similar_indices.append(j)
                if len(similar_indices) >= max_group_size:
                    break
        
        # Create group
        if len(similar_indices) > 1:  # Only create groups with multiple items
            group = []
            for idx in similar_indices:
                group.append({
                    'url': urls[idx],
                    'description': descriptions[idx],
                    'similarity_to_first': float(similarity_matrix[i][idx])
                })
                used_indices.add(idx)
            groups.append(group)
        else:
            used_indices.add(i)
    
    print(f"Created {len(groups)} groups of similar webpages")
    return groups


def save_retrieval_index(index: Dict, filepath: str):
    """Save the retrieval index to disk."""
    with open(filepath, 'wb') as f:
        pickle.dump(index, f)
    print(f"Webpage retrieval index saved to {filepath}")


def load_retrieval_index(filepath: str) -> Dict:
    """Load the retrieval index from disk."""
    with open(filepath, 'rb') as f:
        index = pickle.load(f)
    print(f"Webpage retrieval index loaded from {filepath}")
    print(f"Index contains {index.get('total_webpages', 'unknown')} webpages")
    print(f"Created with model: {index.get('model_name', 'unknown')}")
    return index


def export_results_to_json(results: List[Dict], output_file: str):
    """Export retrieval results to JSON format."""
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"Results exported to {output_file}")


def main():
    parser = argparse.ArgumentParser(description='Create and test a retrieval index for webpage descriptions')
    parser.add_argument('descriptions_file', help='Path to the JSON file with webpage descriptions')
    parser.add_argument('output_index', help='Path to save the retrieval index (pkl file)')
    parser.add_argument('--model', default='all-MiniLM-L6-v2', 
                       help='Sentence transformer model to use (default: all-MiniLM-L6-v2)')
    parser.add_argument('--query', help='Optional query to test retrieval')
    parser.add_argument('--functionality', nargs='+', 
                       help='List of functionality keywords to search for')
    parser.add_argument('--top-k', type=int, default=10, 
                       help='Number of top results to return (default: 10)')
    parser.add_argument('--similarity-threshold', type=float, default=0.3, 
                       help='Minimum similarity score (default: 0.3)')
    parser.add_argument('--group-similar', action='store_true', 
                       help='Group similar webpages together')
    parser.add_argument('--group-threshold', type=float, default=0.7,
                       help='Similarity threshold for grouping (default: 0.7)')
    parser.add_argument('--export-json', help='Export results to JSON file')
    parser.add_argument('--verbose', action='store_true', help='Enable verbose output')
    
    args = parser.parse_args()
    
    # Validate input file exists
    if not os.path.exists(args.descriptions_file):
        print(f"Error: Descriptions file '{args.descriptions_file}' not found")
        return
    
    # Load webpage descriptions
    try:
        descriptions = load_webpage_descriptions(args.descriptions_file)
    except Exception as e:
        print(f"Error loading descriptions: {e}")
        return
    
    if not descriptions:
        print("Error: No descriptions found in the input file")
        return
    
    # Create the retrieval index
    print("\nCreating webpage retrieval index...")
    try:
        retrieval_index = create_webpage_retrieval_index(descriptions, args.model)
    except Exception as e:
        print(f"Error creating retrieval index: {e}")
        return
    
    # Save the index
    save_retrieval_index(retrieval_index, args.output_index)
    
    # Test functionality-based search
    if args.functionality:
        print(f"\nSearching for webpages with functionality: {', '.join(args.functionality)}")
        functionality_results = find_webpages_by_functionality(
            args.functionality, retrieval_index, args.top_k, args.similarity_threshold
        )
        
        print(f"Found {len(functionality_results)} webpages with matching functionality:")
        for i, result in enumerate(functionality_results, 1):
            print(f"{i}. URL: {result['url']}")
            print(f"   Similarity: {result['similarity_score']:.3f}")
            if args.verbose:
                print(f"   Description: {result['description'][:200]}{'...' if len(result['description']) > 200 else ''}")
            print()
        
        if args.export_json:
            json_file = args.export_json.replace('.json', '_functionality.json')
            export_results_to_json(functionality_results, json_file)
    
    # Test query-based retrieval
    if args.query:
        print(f"\nTesting retrieval with query: '{args.query[:100]}{'...' if len(args.query) > 100 else ''}'")
        similar_webpages = retrieve_similar_webpages(
            args.query, retrieval_index, args.top_k, args.similarity_threshold
        )
        
        print(f"Found {len(similar_webpages)} similar webpages:")
        for i, webpage in enumerate(similar_webpages, 1):
            print(f"{i}. URL: {webpage['url']}")
            print(f"   Similarity: {webpage['similarity_score']:.3f}")
            if args.verbose:
                print(f"   Description: {webpage['description'][:200]}{'...' if len(webpage['description']) > 200 else ''}")
            print()
        
        if args.export_json:
            json_file = args.export_json.replace('.json', '_query.json')
            export_results_to_json(similar_webpages, json_file)
    
    # Group similar webpages
    if args.group_similar:
        print(f"\nGrouping similar webpages...")
        groups = group_similar_webpages(retrieval_index, args.group_threshold)
        
        print(f"Found {len(groups)} groups of similar webpages:")
        for i, group in enumerate(groups, 1):
            print(f"\nGroup {i} ({len(group)} webpages):")
            for j, webpage in enumerate(group, 1):
                print(f"  {j}. {webpage['url']} (similarity: {webpage['similarity_to_first']:.3f})")
                if args.verbose:
                    print(f"      {webpage['description'][:150]}{'...' if len(webpage['description']) > 150 else ''}")
        
        if args.export_json:
            json_file = args.export_json.replace('.json', '_groups.json')
            export_results_to_json(groups, json_file)
    
    print(f"\n✅ Retrieval index creation completed!")
    print(f"📊 Index contains {retrieval_index['total_webpages']} webpages")
    print(f"🔍 Use the index for semantic search of similar webpages")


if __name__ == "__main__":
    main()